FROM starudream/alpine AS builder

ARG UPX_VERSION=3.96

RUN apk add --no-cache wget \
    && wget -qO /tmp/upx.tar.xz https://github.com/upx/upx/releases/download/v${UPX_VERSION}/upx-${UPX_VERSION}-arm64_linux.tar.xz \
    && tar Jxf /tmp/upx.tar.xz -C /tmp && mv /tmp/upx-${UPX_VERSION}-arm64_linux/upx /tmp/upx && chmod +x /tmp/upx

FROM starudream/alpine-glibc

COPY --from=builder /tmp/upx /usr/bin/upx

CMD upx
