FROM starudream/alpine AS builder

ARG GLIBC_VERSION=2.33-r0

RUN apk add --no-cache wget \
    && wget -qO /tmp/glibc.apk https://github.com/SatoshiPortal/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}-aarch64.apk

FROM starudream/alpine

COPY --from=builder /tmp/glibc.apk /tmp/glibc.apk

RUN apk add --allow-untrusted /tmp/glibc.apk && rm -rf /tmp/glibc.apk
