name: alpine-glibc
on:
  push:
    branches:
      - master
    paths:
      - 'alpine-glibc/**'
  schedule:
    - cron: '0 1 * * *'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build
        run: |
          cd alpine-glibc
          echo "${{secrets.DOCKER_TOKEN}}" | docker login -u starudream --password-stdin
          docker build -t starudream/alpine-glibc:latest .
          docker push starudream/alpine-glibc:latest
