name: alpine
on:
  push:
    path:
      - 'alpine/**'
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build
        run: |
          cd alpine
          echo "${{secrets.DOCKER_TOKEN}}" | docker login -u starudream --password-stdin
          docker build -t starudream/alpine:latest .
          docker push starudream/alpine:latest
