name: Docker

on:
  - push

jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: false

  alpine-glibc:
    runs-on: ubuntu-latest
    needs:
      - alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: false

  baidu-su:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
      - golang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: starudream/${{ github.job }}
          path: ${{ github.job }}
          token: ${{ secrets.PAGE_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: false

  clash:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: false

  clash-speedtest:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
      - golang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: starudream/${{ github.job }}
          path: ${{ github.job }}
          token: ${{ secrets.PAGE_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: false

  dwyl-hits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: false

  cronjob:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
      - golang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: starudream/${{ github.job }}
          path: ${{ github.job }}
          token: ${{ secrets.PAGE_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: false

  frpc:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: false

  frps:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: false

  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: false

  h5ai:
    runs-on: ubuntu-latest
    needs:
      - alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: false

  kubectl:
    runs-on: ubuntu-latest
    needs:
      - alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: false

  node:
    runs-on: ubuntu-latest
    needs:
      - alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: false

  npc:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: false

  nps:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: false

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: false

  zerotier:
    runs-on: ubuntu-latest
    needs:
      - alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: false
