name: Docker

on:
  - push

jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  alpine-glibc:
    runs-on: ubuntu-latest
    needs:
      - alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  alpine-glibc-upx:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
      - upx
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  baidu-su:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
      - golang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: starudream/${{ github.job }}
          path: ${{ github.job }}
          token: ${{ secrets.PAGE_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  clash:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc-upx
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  clash-speedtest:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
      - golang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: starudream/${{ github.job }}
          path: ${{ github.job }}
          token: ${{ secrets.PAGE_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  dwyl-hits:
    runs-on: ubuntu-latest
    needs:
      - node
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  cronjob:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
      - golang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: starudream/${{ github.job }}
          path: ${{ github.job }}
          token: ${{ secrets.PAGE_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  frpc:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc-upx
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  frps:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc-upx
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  golang:
    runs-on: ubuntu-latest
    needs:
      - upx
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  h5ai:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  kubectl:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
      - alpine-glibc-upx
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  npc:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc-upx
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  nps:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc-upx
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  upx:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  zerotier:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}
