name: Docker
on:
  - push
env:
  USERNAME: starudream
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
jobs:
  alpine:
    name: alpine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: bash build.sh alpine
  alpine-glibc:
    name: alpine-glibc
    runs-on: ubuntu-latest
    needs:
      - alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: bash build.sh alpine-glibc
  baidu-su:
    name: baidu-su
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
      - golang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: starudream/baidu-su
          path: baidu-su
          token: ${{ secrets.PAGE_PAT }}
      - name: Build
        run: bash build.sh baidu-su
  clash:
    name: clash
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: bash build.sh clash
  clash-speedtest:
    name: clash-speedtest
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
      - golang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: starudream/clash-speedtest
          path: clash-speedtest
          token: ${{ secrets.PAGE_PAT }}
      - name: Build
        run: bash build.sh clash-speedtest
  cronjob:
    name: cronjob
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
      - golang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: starudream/cronjob
          path: cronjob
          token: ${{ secrets.PAGE_PAT }}
      - name: Build
        run: bash build.sh cronjob
  frpc:
    name: frpc
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: bash build.sh frpc
  frps:
    name: frps
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: bash build.sh frps
  golang:
    name: golang
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: bash build.sh golang
  h5ai:
    name: h5ai
    runs-on: ubuntu-latest
    needs:
      - alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: bash build.sh h5ai
  kubectl:
    name: kubectl
    runs-on: ubuntu-latest
    needs:
      - alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: bash build.sh kubectl
