name: Docker

on:
  - push

env:
  DOCKER_USERNAME: starudream

jobs:

  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          tags: ${{ env.DOCKER_USERNAME }}/${{ github.job }}
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          cache-from: type=gha,scope=${{ github.job }}
          cache-to: type=gha,mode=max,scope=${{ github.job }}

  alpine-glibc:
    runs-on: ubuntu-latest
    needs:
      - alpine
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          tags: ${{ env.DOCKER_USERNAME }}/${{ github.job }}
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          cache-from: type=gha,scope=${{ github.job }}
          cache-to: type=gha,mode=max,scope=${{ github.job }}

  alpine-glibc-upx:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          tags: ${{ env.DOCKER_USERNAME }}/${{ github.job }}
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          cache-from: type=gha,scope=${{ github.job }}
          cache-to: type=gha,mode=max,scope=${{ github.job }}

  clash:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc-upx
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          tags: ${{ env.DOCKER_USERNAME }}/${{ github.job }}
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          cache-from: type=gha,scope=${{ github.job }}
          cache-to: type=gha,mode=max,scope=${{ github.job }}

  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          tags: ${{ env.DOCKER_USERNAME }}/${{ github.job }}
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          cache-from: type=gha,scope=${{ github.job }}
          cache-to: type=gha,mode=max,scope=${{ github.job }}

  sub-converter:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          tags: ${{ env.DOCKER_USERNAME }}/${{ github.job }}
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          cache-from: type=gha,scope=${{ github.job }}
          cache-to: type=gha,mode=max,scope=${{ github.job }}
