name: Docker

on:
  - push

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:

  alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  alpine-glibc:
    runs-on: ubuntu-latest
    needs:
      - alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  alpine-glibc-upx:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
      - upx
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  clash:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc-upx
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  clash-speedtest:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
      - golang
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: starudream/${{ github.job }}
          path: ${{ github.job }}
          token: ${{ secrets.PAGE_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  creative-apartment:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
      - golang
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: starudream/${{ github.job }}
          path: ${{ github.job }}
          token: ${{ secrets.PAGE_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  frpc:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc-upx
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  frps:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc-upx
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  golang:
    runs-on: ubuntu-latest
    needs:
      - upx
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  h5ai:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  kubectl:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc-upx
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  node-14:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  node-16:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  npc:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc-upx
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  nps:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc-upx
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  sub-converter:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  upx:
    runs-on: ubuntu-latest
    needs:
      - alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check if Files Changed
        id: changes
        run: |
          if [ $(git diff --name-only HEAD^ HEAD | grep "^${{ github.job }}/" | wc -l) -gt 0 ]; then
            echo "::set-output name=FILE_CHANGED::true"
          else
            echo "::set-output name=FILE_CHANGED::false"
          fi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: ${{ steps.changes.outputs.FILE_CHANGED == 'true' }}
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: ${{ steps.changes.outputs.FILE_CHANGED == 'true' }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: ${{ steps.changes.outputs.FILE_CHANGED == 'true' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        if: ${{ steps.changes.outputs.FILE_CHANGED == 'true' }}
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  wake-on-lan:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
      - golang
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: starudream/${{ github.job }}
          path: ${{ github.job }}
          token: ${{ secrets.PAGE_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}

  webhook-forward:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
      - golang
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: starudream/${{ github.job }}
          path: ${{ github.job }}
          token: ${{ secrets.PAGE_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          file: ${{ github.job }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          push: ${{ github.event_name != 'pull_request' }}
