name: Docker

permissions:
  packages: write

on:
  workflow_dispatch:
  push: { branches: [ "master" ] }

jobs:

  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: starudream
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: starudream
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          tags: starudream/${{ github.job }},ghcr.io/starudream/${{ github.job }}
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          cache-from: type=gha,scope=${{ github.job }}
          cache-to: type=gha,mode=max,scope=${{ github.job }}

  alpine-glibc:
    runs-on: ubuntu-latest
    needs:
      - alpine
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: starudream
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: starudream
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          tags: starudream/${{ github.job }},ghcr.io/starudream/${{ github.job }}
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          cache-from: type=gha,scope=${{ github.job }}
          cache-to: type=gha,mode=max,scope=${{ github.job }}

  clash:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: starudream
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: starudream
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          tags: starudream/${{ github.job }},ghcr.io/starudream/${{ github.job }}
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          cache-from: type=gha,scope=${{ github.job }}
          cache-to: type=gha,mode=max,scope=${{ github.job }}

  derper:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
      - golang
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: starudream
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: starudream
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          tags: starudream/${{ github.job }},ghcr.io/starudream/${{ github.job }}
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          cache-from: type=gha,scope=${{ github.job }}
          cache-to: type=gha,mode=max,scope=${{ github.job }}

  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: starudream
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: starudream
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          tags: starudream/${{ github.job }},ghcr.io/starudream/${{ github.job }}
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          cache-from: type=gha,scope=${{ github.job }}
          cache-to: type=gha,mode=max,scope=${{ github.job }}

  sub-converter:
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: starudream
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: starudream
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          tags: starudream/${{ github.job }},ghcr.io/starudream/${{ github.job }}
          context: ${{ github.job }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          cache-from: type=gha,scope=${{ github.job }}
          cache-to: type=gha,mode=max,scope=${{ github.job }}
