name: Docker
on:
  - push
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build
        run: |
          for d in $(ls); do
            if [ -d "${d}" ]; then
              cd "${d}"
              docker build .
              cd ..
            fi
          done
