name: Docker-Minio

permissions:
  packages: write

on:
  workflow_dispatch:

jobs:

  minio-raw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: starudream
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: starudream
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          tags: starudream/minio:raw,ghcr.io/starudream/minio:raw
          context: minio
          file: minio/Dockerfile-raw
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          cache-from: type=gha,scope=${{ github.job }}
          cache-to: type=gha,mode=max,scope=${{ github.job }}

  minio-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: starudream
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: starudream
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          tags: starudream/minio:ui,ghcr.io/starudream/minio:ui
          context: minio
          file: minio/Dockerfile-ui
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          cache-from: type=gha,scope=${{ github.job }}
          cache-to: type=gha,mode=max,scope=${{ github.job }}
