name: docker-postgres

permissions:
  packages: write

on:
  workflow_dispatch:
  push: { paths: [ 'postgres/**' ] }

jobs:

  postgres-17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: starudream
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: starudream
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          tags: starudream/postgres:17,ghcr.io/starudream/postgres:17
          context: postgres
          file: postgres/Dockerfile-17
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          cache-from: type=gha,scope=${{ github.job }}
          cache-to: type=gha,mode=max,scope=${{ github.job }}
