name: sync-acr

permissions:
  packages: read

on:
  registry_package:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  sync-acr:
    runs-on: ubuntu-latest
    env:
      SKOPEO_VERSION: v1.19.0
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: starudream
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: starudream
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: sync
        run: |
          mkdir -p $(pwd)/bin
          wget -q --show-progress --progress dot:giga -O $(pwd)/bin/skopeo https://github.com/lework/skopeo-binary/releases/download/${{ env.SKOPEO_VERSION }}/skopeo-linux-amd64 && chmod +x $(pwd)/bin/skopeo
          SKOPEO_PATH=$(pwd)/bin/skopeo ./sync-images.sh
